apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: kustomize
spec:
  promotionTemplate:
    versionSource:
      file: guestbook-ui-deployment.yaml
      jsonPath: $.*.*.*.*.*.image
  concurrency: queue
