apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: kustomize
spec:
  promotionTemplate:
    versionSource:
      file: kustomization.yaml
      jsonPath: $.*.*.newTag
  concurrency: queue
