apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: trio
spec:
  promotionFlows:
    - name: prod-dev
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - promote
  promotionTemplate:
    versionSource:
      file: values.yaml
      jsonPath: $.*.tag
    promotion:
      values.yaml:
        jsonPaths:
          - $.image
          - $.replicaCount
  concurrency: queue
