apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: adf
  annotations:
    description: ""
spec:
  triggerEnvironment: test
  steps:
    - environment: prod
      dependsOn:
        - test
      policy:
        action: commit
