apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: prod-dev
  annotations:
    description: ""
spec:
  triggerEnvironment: prod
  steps:
    - environment: dev
      dependsOn:
        - prod
      policy:
        action: commit
